# Generated by Django 3.2.2 on 2022-01-28 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220125_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couples',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='couples',
            name='user2',
        ),
        migrations.AddField(
            model_name='couples',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
